version: "3.8"

services:
  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/
      - ./app/log:/var/log/uwsgi/
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/build:/usr/share/nginx/html  # Reactのビルドファイル
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - uwsgi
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
