const appEnv = process.env.REACT_APP_ENV; // local or deploy

export const BASE_PATH =
  appEnv === "deploy" ? "/shigachat" : "/";

export const API_BASE_URL =
  appEnv === "deploy"
    ? "https://si-lab.org/shigachat/api"
    : "http://localhost:8000";

export const translations = {
  ja: {
    home: "ホーム",
    keyword: "キーワード検索",
    logout: "ログアウト",
    menu: "メニュー",
    welcome: "ようこそ！",
    guest: "ゲスト",
    askQuestion: "質問してみよう",
    disclaimer: "ShigaChatの情報は正確でない場合があります",
    questionLabel: "質問を入力：",
    placeholder: "ここに質問を入力してください...",
    askButton: "質問する",
    generatingAnswer: "回答を生成しています...",
    answer: "回答：",
    similarQuestions: "参照した質問と回答：",
    noSimilarWarning: "類似質問はありません。回答は正確でない可能性があります。",
    sortByDate: "日時順",
    sortBySimilarity: "類似度順",
    registerquestion: "🛠️Q&Aを登録する",
    error: "エラーが発生しました：",
    official: "公式",
    publicToggle: "公開",
    privateToggle: "非公開",
    makepublicToggle: "質問を公開する",
    makeprivateToggle: "質問を公開しない",
    enterquestion: "質問を入力してください",
    failedtopost: "質問の投稿に失敗しました",
    failtogetanswer: "回答の取得に失敗しました",
    failtoupdate: "更新に失敗しました。",
    timeUnknown: "日時不明",
    keywordSearch: "キーワード検索",
    enterKeyword: "キーワードを入力...",
    search: "検索",
    noResults: "検索結果がありません。",
    errorLogin: "ログインが必要です。",
    keyworderror: "キーワードエラー",
    category: "カテゴリ",
    categorySearch: "カテゴリ検索",
    select: "下から選択してください",
    loading: "読み込み中...",
    noQuestions: "このカテゴリには質問がありません。",
    questionDate: "最終更新日時：",
    backButton: "カテゴリ検索画面に戻る",
    categorynotfound: "カテゴリが見つかりません。",
    viewedHistory: "閲覧履歴を見る",
    noHistory: "閲覧履歴はありません。",
    viewDate: "閲覧日：",
    clear: "閲覧履歴を削除",
    questionhistory: "質問履歴",
    publicerror: "公開ステータスの変更に失敗しました。",
    changecategory: "カテゴリを変更する",
    selectcategory: "カテゴリを選択",
    moveto: "カテゴリを移動：",
    cancel: "キャンセル",
    currentCategory: "現在のカテゴリ",
    personal: "個人",
    global: "全体",
    noNotifications: "通知はありません。",
    questionmanagement: "質問管理",
    newChat: "新しいチャット",
    threads: "スレッド",
    noThreads: "まだスレッドがありません",
    renameThread: "スレッド名を変更",
    confirmDeleteThread: "スレッドを削除しますか？",
    threadDeletedSuccess: "スレッドを削除しました",
    threadDeletedDescription: "スレッドが正常に削除されました",
    threadDeletedError: "スレッドの削除に失敗しました",
    threadDeletedErrorDescription: "エラーが発生しました。もう一度お試しください。",
    similarityLabel: "絞り込み強度",
    similarityDefaultLabel: "既定",
    similarityLow: "弱い",
    similarityHigh: "強い",
    screenSize: "画面サイズ",
    widthSmall: "小",
    widthMedium: "中",
    widthLarge: "大",
    register: "Q&Aを登録しました",
    qtext: "質問：",
    unpublic: "非公開",
    unofficial: "非公式",
    close: "閉じる",
    questionerror: "質問を入力してください。",
    answererror: "回答を入力してください。",
    register_question: "Q&Aを登録する",
    edit: "編集",
    save: "保存",
    give_official: "公式マークを付与する",
    takeaway_official: "公式マークを外す",
    delete: "削除",
    confirmDelete: "この質問を削除してもよろしいですか？",
    answerupdated: "回答が更新されました！",
    unofficialize: "公式マークを削除しますか？",
    officialize: "公式マークを付与しますか？",
    categorychanged: "カテゴリが変更されました！",
    failtochangecategory: "カテゴリの変更に失敗しました。",
    nickname: "名前",
    password: "パスワード",
    login: "ログイン",
    registerPrompt: "↓↓↓↓ 新規登録はこちら ↓↓↓↓",
    successLogin: "ログインに成功しました！",
    signUp: "新規登録",
    age: "年齢",
    gender: "性別",
    spokenLanguage: "使用言語",
    male: "男性",
    female: "女性",
    other: "その他",
    errorEmptyFields: "ニックネームとパスワードを入力してください。",
    errorInvalidLogin: "ニックネームまたはパスワードが正しくありません。",
    errorServer: "ログインに失敗しました。正しい名前とパスワードを入力してください。",
    errorAllFields: "すべての項目を入力してください！",
    successRegistration: "登録が完了しました！",
    errorRegistration: "登録に失敗しました",
    selectLanguage: "言語を選択",
    editor: "編集者",
    openInAdmin: "質問管理で開く",
    historyOpen: "過去の回答を見る",
    historyClose: "履歴を閉じる",
    historyEmpty: "履歴はありません。",
    diffShow: "差分を表示",
    diffHide: "差分を隠す",
    diffCaption: "この版 → 次の版との差分",
    actionButton: "アクション",
    actionTranslate: "翻訳",
    actionSummarize: "要約",
    actionSimplify: "わかりやすく",
    actionApplied: "アクション結果を入力欄に反映しました",
    actionLabel: "アクション",
    noRecentAnswer: "直近の回答がありません",
    actionApplyPrefix: "",
    actionApplySuffix: "を適用",
    notSelected: "選択されていません",
    // Tooltips
    tooltipHome: "ホーム画面",
    tooltipKeywordSearch: "キーワード検索",
    tooltipCategorySearch: "カテゴリ検索",
    tooltipQuestionManagement: "質問管理",
    tooltipNotifications: "通知を確認します",
    tooltipLanguageSelect: "表示言語を変更します",
    tooltipSidebarToggle: "サイドバーの表示/非表示を切り替えます",
    tooltipUserMenu: "ユーザーメニューを開きます",
  },
  en: {
    home: "Home",
    keyword: "Keyword Search",
    logout: "Logout",
    menu: "Menu",
    welcome: "Welcome!",
    guest: "Guest",
    askQuestion: "Ask anything",
    disclaimer: "ShigaChat information may be inaccurate.",
    questionLabel: "Enter your question:",
    placeholder: "Type your question here...",
    askButton: "Ask Question",
    generatingAnswer: "Generating answer...",
    answer: "Answer: ",
    similarQuestions: "Referenced Questions and Answers:",
    noSimilarWarning: "No similar questions found. The answer may be inaccurate.",
    sortByDate: "Sort by Date",
    sortBySimilarity: "Sort by Similarity",
    registerquestion: "🛠️Register Q&A",
    error: "Error occurred: ",
    official: "Official",
    publicToggle: "Public",
    privateToggle: "Private",
    makepublicToggle: "Make Question public",
    makeprivateToggle: "Keep Question private", 
    enterquestion: "Please enter a question",
    failedtopost: "Failed to post question",
    failtogetanswer: "Failed to get answer",
    failtoupdate: "Failed to update.",
    timeUnknown: "Time unknown",
    keywordSearch: "Keyword Search",
    enterKeyword: "Enter a keyword...",
    search: "Search",
    noResults: "No results found.",
    errorLogin: "Login required.",
    keyworderror: "Keyword error",
    category: "Category",
    categorySearch: "Category Search",
    select: "Please select from below",
    loading: "Loading...",
    noQuestions: "No questions in this category.",
    questionDate: "Last updated date and time:",
    backButton: "Back to Category Search",
    categorynotfound: "Category not found.",
    viewedHistory: "View History",
    noHistory: "No history available.",
    viewDate: "Viewed on:",
    clear: "Clear Viewing History",
    questionhistory: "Question History",
    publicerror: "Failed to change public status.",
    changecategory: "Change Category",
    selectcategory: "Select Category",
    moveto: "Move to category: ",
    cancel: "Cancel",
    currentCategory: "Current Category",
    personal: "Personal",
    global: "General",
    noNotifications: "No notifications.",
    newChat: "New Chat",
    threads: "Threads",
    noThreads: "No threads yet",
    renameThread: "Rename Thread",
    confirmDeleteThread: "Delete this thread?",
    threadDeletedSuccess: "Thread deleted",
    threadDeletedDescription: "The thread has been successfully deleted",
    threadDeletedError: "Failed to delete thread",
    threadDeletedErrorDescription: "An error occurred. Please try again.",
    similarityLabel: "Match strictness",
    similarityDefaultLabel: "Default",
    similarityLow: "Low",
    similarityHigh: "High",
    screenSize: "Screen size",
    widthSmall: "S",
    widthMedium: "M",
    widthLarge: "L",
    questionmanagement: "Question Management",
    register: "Q&A has been registered",
    qtext: "Question: ",
    unpublic: "Unpublic",
    unofficial: "Unofficial",
    close: "Close",
    questionerror: "Please enter a question.",
    answererror: "Please enter an answer.",
    register_question: "Register Q&A",
    edit: "Edit",
    save: "Save",
    give_official: "Grant Official Mark",
    takeaway_official: "Remove Official Mark",
    delete: "Delete",
    confirmDelete: "Are you sure you want to delete this question?",
    answerupdated: "Answer has been updated!",
    unofficialize: "Do you want to remove the official mark?",
    officialize: "Do you want to grant the official mark?",
    categorychanged: "Category has been changed!",
    failtochangecategory: "Failed to change category.",
    nickname: "Name",
    password: "Password",
    login: "Login",
    registerPrompt: "↓↓↓↓ Click here to register ↓↓↓↓",
    successLogin: "Login successful!",
    signUp: "Sign Up",
    age: "Age",
    gender: "Gender",
    spokenLanguage: "Spoken Language",
    male: "Male",
    female: "Female",
    other: "Other",
    errorEmptyFields: "Please enter your nickname and password.",
    errorInvalidLogin: "Invalid nickname or password.",
    errorServer: "Login failed. Please enter the correct name and password.",
    errorAllFields: "Please fill in all fields!",
    successRegistration: "Registration successful!",
    errorRegistration: "Registration failed",
    selectLanguage: "Select Language",
    editor: "editor",
    openInAdmin: "Open in Admin",
    historyOpen: "View revision history",
    historyClose: "Close history",
    historyEmpty: "No history.",
    diffShow: "Show diff",
    diffHide: "Hide diff",
    diffCaption: "Diff: this version → next",
    actionButton: "Actions",
    actionTranslate: "Translate",
    actionSummarize: "Summarize",
    actionSimplify: "Simplify",
    actionApplied: "Applied result to the input field",
    actionLabel: "Action",
    noRecentAnswer: "No recent assistant answer found",
    actionApplyPrefix: "",
    actionApplySuffix: " applied",
    notSelected: "Not selected",
    // Tooltips
    tooltipHome: "Home Screen",
    tooltipKeywordSearch: "Keyword Search",
    tooltipCategorySearch: "Category Search",
    tooltipQuestionManagement: "Question Management",
    tooltipNotifications: "Check notifications",
    tooltipLanguageSelect: "Change display language",
    tooltipSidebarToggle: "Toggle sidebar visibility",
    tooltipUserMenu: "Open user menu",
  },  
  zh: {
    home: "首页",
    keyword: "关键词搜索",
    logout: "登出",
    menu: "菜单",
    welcome: "欢迎！",
    guest: "访客",
    askQuestion: "尽管提问",
    disclaimer: "ShigaChat 的信息可能不准确。",
    questionLabel: "输入你的问题：",
    placeholder: "请在此输入你的问题...",
    askButton: "提交问题",
    generatingAnswer: "正在生成回答...",
    answer: "回答：",
    similarQuestions: "参考问题和回答：",
    noSimilarWarning: "未找到类似问题。回答可能不够准确。",
    sortByDate: "按日期排序",
    sortBySimilarity: "按相似度排序",
    registerquestion: "🛠️注册问答",
    error: "发生错误：",
    official: "官方",
    publicToggle: "公开",
    privateToggle: "私密",
    makepublicToggle: "公开此问题",
    makeprivateToggle: "保留为私密", 
    enterquestion: "请输入问题",
    failedtopost: "提交问题失败",
    failtogetanswer: "获取回答失败",
    failtoupdate: "更新失败。",
    timeUnknown: "时间未知",
    keywordSearch: "关键词搜索",
    enterKeyword: "请输入关键词...",
    search: "搜索",
    noResults: "没有找到结果。",
    errorLogin: "请登录。",
    keyworderror: "关键词错误",
    category: "类别",
    categorySearch: "类别搜索",
    select: "请从下面选择",
    loading: "加载中...",
    noQuestions: "该类别下没有问题。",
    questionDate: "上次更新日期和時間：",
    backButton: "返回类别搜索",
    categorynotfound: "未找到类别。",
    viewedHistory: "浏览历史",
    noHistory: "无浏览记录。",
    viewDate: "查看时间：",
    clear: "清除浏览记录",
    questionhistory: "问题历史记录",
    publicerror: "更改公开状态失败。",
    changecategory: "更改类别",
    selectcategory: "选择类别",
    moveto: "移动到类别：",
    cancel: "取消",
    currentCategory: "当前类别",
    personal: "个人",
    global: "全部",
    noNotifications: "无通知。",
    questionmanagement: "问题管理",
    newChat: "新聊天",
    threads: "线程",
    noThreads: "还没有线程",
    renameThread: "重命名线程",
    confirmDeleteThread: "删除此线程？",
    threadDeletedSuccess: "线程已删除",
    threadDeletedDescription: "线程已成功删除",
    threadDeletedError: "删除线程失败",
    threadDeletedErrorDescription: "发生错误。请重试。",
    similarityLabel: "匹配严格度",
    similarityDefaultLabel: "默认",
    similarityLow: "低",
    similarityHigh: "高",
    screenSize: "屏幕大小",
    widthSmall: "小",
    widthMedium: "中",
    widthLarge: "大",
    register: "问答發布",
    qtext: "问题：",
    unpublic: "不公开",
    unofficial: "非官方",
    close: "关闭",
    questionerror: "请输入问题。",
    answererror: "请输入回答。",
    register_question: "註冊问答",
    edit: "编辑",
    save: "保存",
    give_official: "授予官方标记",
    takeaway_official: "移除官方标记",
    delete: "删除",
    confirmDelete: "你确定要删除此问题吗？",
    answerupdated: "回答已更新！",
    unofficialize: "是否移除官方标记？",
    officialize: "是否授予官方标记？",
    categorychanged: "类别已更改！",
    failtochangecategory: "更改类别失败。",
    nickname: "姓名",
    password: "密码",
    login: "登录",
    registerPrompt: "↓↓↓↓ 点击此处注册 ↓↓↓↓",
    successLogin: "登录成功！",
    signUp: "注册",
    age: "年龄",
    gender: "性别",
    spokenLanguage: "使用语言",
    male: "男",
    female: "女",
    other: "其他",
    errorEmptyFields: "请输入昵称和密码。",
    errorInvalidLogin: "昵称或密码错误。",
    errorServer: "登录失败。请输入正确的姓名和密码。",
    errorAllFields: "请填写所有字段！",
    successRegistration: "注册成功！",
    errorRegistration: "注册失败",
    selectLanguage: "选择语言",
    editor: "编辑",
    openInAdmin: "在管理中打开",
    historyOpen: "查看历史",
    historyClose: "关闭历史",
    historyEmpty: "没有历史。",
    diffShow: "显示差异",
    diffHide: "隐藏差异",
    diffCaption: "差异：此版本 → 下一个",
    actionButton: "操作",
    actionTranslate: "翻译",
    actionSummarize: "摘要",
    actionSimplify: "通俗易懂",
    actionApplied: "已将结果填入输入框",
    actionLabel: "操作",
    noRecentAnswer: "没有可用的最新回答",
    actionApplyPrefix: "应用: ",
    actionApplySuffix: "",
    notSelected: "未选择",
    // Tooltips
    tooltipHome: "主页",
    tooltipKeywordSearch: "关键词搜索",
    tooltipCategorySearch: "分类搜索",
    tooltipQuestionManagement: "问题管理",
    tooltipNotifications: "查看通知",
    tooltipLanguageSelect: "更改显示语言",
    tooltipSidebarToggle: "切换侧边栏显示/隐藏",
    tooltipUserMenu: "打开用户菜单",
  },
  vi: {
    home: "Trang chủ",
    keyword: "Tìm kiếm từ khóa",
    logout: "Đăng xuất",
    menu: "Menu",
    welcome: "Chào mừng!",
    guest: "Khách",
    askQuestion: "Hãy hỏi bất cứ điều gì",
    disclaimer: "Thông tin của ShigaChat có thể không chính xác.",
    questionLabel: "Nhập câu hỏi của bạn:",
    placeholder: "Nhập câu hỏi tại đây...",
    askButton: "Đặt câu hỏi",
    generatingAnswer: "Đang tạo câu trả lời...",
    answer: "Câu trả lời: ",
    similarQuestions: "Câu hỏi và câu trả lời tham khảo:",
    noSimilarWarning: "Không tìm thấy câu hỏi tương tự. Câu trả lời có thể không chính xác.",
    sortByDate: "Sắp xếp theo ngày",
    sortBySimilarity: "Sắp xếp theo mức độ tương tự",
    registerquestion: "🛠️Đăng ký câu hỏi và câu trả lời",
    error: "Đã xảy ra lỗi: ",
    official: "Chính thức",
    publicToggle: "Công khai",
    privateToggle: "Riêng tư",
    makepublicToggle: "Công khai câu hỏi",
    makeprivateToggle: "Giữ câu hỏi riêng tư", 
    enterquestion: "Vui lòng nhập câu hỏi",
    failedtopost: "Gửi câu hỏi thất bại",
    failtogetanswer: "Không thể lấy câu trả lời",
    failtoupdate: "Cập nhật thất bại.",
    timeUnknown: "Không rõ thời gian",
    keywordSearch: "Tìm kiếm từ khóa",
    enterKeyword: "Nhập từ khóa...",
    search: "Tìm kiếm",
    noResults: "Không tìm thấy kết quả.",
    errorLogin: "Yêu cầu đăng nhập.",
    keyworderror: "Lỗi từ khóa",
    category: "Danh mục",
    categorySearch: "Tìm kiếm danh mục",
    select: "Vui lòng chọn từ bên dưới",
    loading: "Đang tải...",
    noQuestions: "Không có câu hỏi nào trong danh mục này.",
    questionDate: "Ngày và giờ cập nhật lần cuối:",
    backButton: "Quay lại tìm kiếm danh mục",
    categorynotfound: "Không tìm thấy danh mục.",
    viewedHistory: "Lịch sử đã xem",
    noHistory: "Không có lịch sử.",
    viewDate: "Xem vào:",
    clear: "Xóa lịch sử đã xem",
    questionhistory: "Lịch sử câu hỏi",
    publicerror: "Thay đổi trạng thái công khai thất bại.",
    changecategory: "Thay đổi danh mục",
    selectcategory: "Chọn danh mục",
    moveto: "Chuyển đến danh mục: ",
    cancel: "Hủy",
    currentCategory: "Danh mục hiện tại",
    personal: "Cá nhân",
    global: "Toàn bộ",
    noNotifications: "Không có thông báo.",
    questionmanagement: "Quản lý câu hỏi",
    newChat: "Cuộc trò chuyện mới",
    threads: "Chủ đề",
    noThreads: "Chưa có chủ đề nào",
    renameThread: "Đổi tên chủ đề",
    confirmDeleteThread: "Xóa chủ đề này?",
    threadDeletedSuccess: "Đã xóa chủ đề",
    threadDeletedDescription: "Chủ đề đã được xóa thành công",
    threadDeletedError: "Xóa chủ đề thất bại",
    threadDeletedErrorDescription: "Đã xảy ra lỗi. Vui lòng thử lại.",
    similarityLabel: "Độ chặt chẽ khớp",
    similarityDefaultLabel: "Mặc định",
    similarityLow: "Thấp",
    similarityHigh: "Cao",
    screenSize: "Kích thước màn hình",
    widthSmall: "S",
    widthMedium: "M",
    widthLarge: "L",
    register: "Câu hỏi và câu trả lời đã được đăng",
    qtext: "Câu hỏi: ",
    unpublic: "Không công khai",
    unofficial: "Không chính thức",
    close: "Đóng",
    questionerror: "Vui lòng nhập câu hỏi.",
    answererror: "Vui lòng nhập câu trả lời.",
    register_question: "Đăng ký câu hỏi và câu trả lời",
    edit: "Chỉnh sửa",
    save: "Lưu",
    give_official: "Gán dấu chính thức",
    takeaway_official: "Xóa dấu chính thức",
    delete: "Xóa",
    confirmDelete: "Bạn có chắc chắn muốn xóa câu hỏi này không?",
    answerupdated: "Câu trả lời đã được cập nhật!",
    unofficialize: "Bạn có muốn xóa dấu chính thức không?",
    officialize: "Bạn có muốn gán dấu chính thức không?",
    categorychanged: "Danh mục đã được thay đổi!",
    failtochangecategory: "Thay đổi danh mục thất bại.",
    nickname: "Tên",
    password: "Mật khẩu",
    login: "Đăng nhập",
    registerPrompt: "↓↓↓↓ Nhấn vào đây để đăng ký ↓↓↓↓",
    successLogin: "Đăng nhập thành công!",
    signUp: "Đăng ký",
    age: "Tuổi",
    gender: "Giới tính",
    spokenLanguage: "Ngôn ngữ sử dụng",
    male: "Nam",
    female: "Nữ",
    other: "Khác",
    errorEmptyFields: "Vui lòng nhập tên người dùng và mật khẩu.",
    errorInvalidLogin: "Tên người dùng hoặc mật khẩu không đúng.",
    errorServer: "Đăng nhập thất bại. Vui lòng nhập đúng tên và mật khẩu.",
    errorAllFields: "Vui lòng điền đầy đủ thông tin!",
    successRegistration: "Đăng ký thành công!",
    errorRegistration: "Đăng ký thất bại",
    selectLanguage: "Chọn ngôn ngữ",
    editor: "biên tập viên",
    openInAdmin: "Mở trong Quản trị",
    historyOpen: "Xem lịch sử",
    historyClose: "Đóng lịch sử",
    historyEmpty: "Không có lịch sử.",
    diffShow: "Hiện khác biệt",
    diffHide: "Ẩn khác biệt",
    diffCaption: "Khác biệt: bản này → bản sau",
    actionButton: "Hành động",
    actionTranslate: "Dịch",
    actionSummarize: "Tóm tắt",
    actionSimplify: "Dễ hiểu hơn",
    actionApplied: "Đã áp dụng kết quả vào ô nhập",
    actionLabel: "Hành động",
    noRecentAnswer: "Không có câu trả lời gần đây",
    actionApplyPrefix: "Áp dụng: ",
    actionApplySuffix: "",
    notSelected: "Chưa chọn",
    // Tooltips
    tooltipHome: "Trang chủ",
    tooltipKeywordSearch: "Tìm từ khóa",
    tooltipCategorySearch: "Tìm danh mục",
    tooltipQuestionManagement: "Quản lý câu hỏi",
    tooltipNotifications: "Kiểm tra thông báo",
    tooltipLanguageSelect: "Thay đổi ngôn ngữ hiển thị",
    tooltipSidebarToggle: "Bật/tắt thanh bên",
    tooltipUserMenu: "Mở menu người dùng",
  },
  ko: {
    home: "홈",
    keyword: "키워드 검색",
    logout: "로그아웃",
    menu: "메뉴",
    welcome: "환영합니다!",
    guest: "게스트",
    askQuestion: "무엇이든 물어보세요",
    disclaimer: "ShigaChat의 정보가 정확하지 않을 수 있습니다.",
    questionLabel: "질문 입력:",
    placeholder: "여기에 질문을 입력하세요...",
    askButton: "질문하기",
    generatingAnswer: "답변 생성 중...",
    answer: "답변: ",
    similarQuestions: "참고한 질문과 답변:",
    noSimilarWarning: "유사한 질문이 없습니다. 답변이 정확하지 않을 수 있습니다.",
    sortByDate: "날짜순 정렬",
    sortBySimilarity: "유사도순 정렬",
    registerquestion: "🛠️질문 답변 등록",
    error: "오류 발생: ",
    official: "공식",
    publicToggle: "공개",
    privateToggle: "비공개",
    makepublicToggle: "질문을 공개하기",
    makeprivateToggle: "질문을 비공개로 유지하기", 
    enterquestion: "질문을 입력하세요",
    failedtopost: "질문 등록 실패",
    failtogetanswer: "답변을 가져오지 못했습니다",
    failtoupdate: "업데이트 실패.",
    timeUnknown: "시간 정보 없음",
    keywordSearch: "키워드 검색",
    enterKeyword: "키워드를 입력하세요...",
    search: "검색",
    noResults: "결과를 찾을 수 없습니다.",
    errorLogin: "로그인이 필요합니다.",
    keyworderror: "키워드 오류",
    category: "카테고리",
    categorySearch: "카테고리 검색",
    select: "아래에서 선택하세요",
    loading: "불러오는 중...",
    noQuestions: "이 카테고리에 질문이 없습니다.",
    questionDate: "최종 갱신 일시:",
    backButton: "카테고리 검색으로 돌아가기",
    categorynotfound: "카테고리를 찾을 수 없습니다.",
    viewedHistory: "조회 기록",
    noHistory: "기록이 없습니다.",
    viewDate: "조회 날짜:",
    clear: "조회 기록 삭제",
    questionhistory: "질문 기록",
    publicerror: "공개 상태 변경 실패",
    changecategory: "카테고리 변경",
    selectcategory: "카테고리 선택",
    moveto: "다음 카테고리로 이동: ",
    cancel: "취소",
    currentCategory: "현재 카테고리",
    personal: "개인",
    global: "전체",
    noNotifications: "알림이 없습니다.",
    questionmanagement: "질문 관리",
    newChat: "새 채팅",
    threads: "스레드",
    noThreads: "아직 스레드가 없습니다",
    renameThread: "스레드 이름 변경",
    confirmDeleteThread: "이 스레드를 삭제하시겠습니까?",
    threadDeletedSuccess: "스레드가 삭제되었습니다",
    threadDeletedDescription: "스레드가 성공적으로 삭제되었습니다",
    threadDeletedError: "스레드 삭제 실패",
    threadDeletedErrorDescription: "오류가 발생했습니다. 다시 시도해주세요.",
    similarityLabel: "일치 기준 엄격도",
    similarityDefaultLabel: "기본값",
    similarityLow: "낮음",
    similarityHigh: "높음",
    screenSize: "화면 크기",
    widthSmall: "소",
    widthMedium: "중",
    widthLarge: "대",
    register: "질문과 답변을 등록했습니다.",
    qtext: "질문: ",
    unpublic: "비공개",
    unofficial: "비공식",
    close: "닫기",
    questionerror: "질문을 입력하세요.",
    answererror: "답변을 입력하세요.",
    register_question: "질문 답변 등록",
    edit: "수정",
    save: "저장",
    give_official: "공식 마크 부여",
    takeaway_official: "공식 마크 제거",
    delete: "삭제",
    confirmDelete: "이 질문을 삭제하시겠습니까?",
    answerupdated: "답변이 업데이트되었습니다!",
    unofficialize: "공식 마크를 제거하시겠습니까?",
    officialize: "공식 마크를 부여하시겠습니까?",
    categorychanged: "카테고리가 변경되었습니다!",
    failtochangecategory: "카테고리 변경 실패",
    nickname: "이름",
    password: "비밀번호",
    login: "로그인",
    registerPrompt: "↓↓↓↓ 여기를 클릭하여 가입 ↓↓↓↓",
    successLogin: "로그인 성공!",
    signUp: "회원가입",
    age: "나이",
    gender: "성별",
    spokenLanguage: "사용 언어",
    male: "남성",
    female: "여성",
    other: "기타",
    errorEmptyFields: "닉네임과 비밀번호를 입력해주세요.",
    errorInvalidLogin: "닉네임 또는 비밀번호가 잘못되었습니다.",
    errorServer: "로그인에 실패했습니다. 올바른 이름과 비밀번호를 입력하세요.",
    errorAllFields: "모든 필드를 입력해주세요!",
    successRegistration: "회원가입 성공!",
    errorRegistration: "회원가입 실패",
    selectLanguage: "언어 선택",
    editor: "편집자",
    openInAdmin: "관리 화면에서 열기",
    historyOpen: "히스토리 보기",
    historyClose: "히스토리 닫기",
    historyEmpty: "히스토리가 없습니다.",
    diffShow: "차이 표시",
    diffHide: "차이 숨기기",
    diffCaption: "차이: 이번 버전 → 다음",
    actionButton: "액션",
    actionTranslate: "번역",
    actionSummarize: "요약",
    actionSimplify: "쉽게 풀기",
    actionApplied: "결과를 입력창에 반영했습니다",
    actionLabel: "액션",
    noRecentAnswer: "최근 답변이 없습니다",
    actionApplyPrefix: "적용: ",
    actionApplySuffix: "",
    notSelected: "선택되지 않음",
    // Tooltips
    tooltipHome: "홈 화면",
    tooltipKeywordSearch: "키워드 검색",
    tooltipCategorySearch: "카테고리 검색",
    tooltipQuestionManagement: "질문 관리",
    tooltipNotifications: "알림 확인",
    tooltipLanguageSelect: "표시 언어 변경",
    tooltipSidebarToggle: "사이드바 표시/숨기기 전환",
    tooltipUserMenu: "사용자 메뉴 열기",
  },
  pt: {
    home: "Início",
    keyword: "Pesquisar por palavra-chave",
    logout: "Sair",
    menu: "Menu",
    welcome: "Bem-vindo!",
    guest: "Convidado",
    askQuestion: "Faça sua pergunta",
    disclaimer: "As informações do ShigaChat podem não ser precisas",
    questionLabel: "Digite sua pergunta:",
    placeholder: "Digite sua pergunta aqui...",
    askButton: "Perguntar",
    generatingAnswer: "Gerando resposta...",
    answer: "Resposta:",
    similarQuestions: "Perguntas e respostas consultadas:",
    noSimilarWarning: "Nenhuma pergunta semelhante encontrada. A resposta pode não ser precisa.",
    sortByDate: "Por data",
    sortBySimilarity: "Por similaridade",
    registerquestion: "🛠️ Registrar Q&A",
    error: "Ocorreu um erro:",
    official: "Oficial",
    publicToggle: "Público",
    privateToggle: "Privado",
    makepublicToggle: "Tornar a pergunta pública",
    makeprivateToggle: "Não tornar a pergunta pública",
    enterquestion: "Digite uma pergunta",
    failedtopost: "Falha ao postar a pergunta",
    failtogetanswer: "Falha ao obter a resposta",
    failtoupdate: "Falha ao atualizar.",
    timeUnknown: "Data/hora desconhecida",
    keywordSearch: "Pesquisa por palavra-chave",
    enterKeyword: "Digite a palavra-chave...",
    search: "Pesquisar",
    noResults: "Nenhum resultado encontrado.",
    errorLogin: "É necessário fazer login.",
    keyworderror: "Erro na palavra-chave",
    category: "Categoria",
    categorySearch: "Pesquisa por categoria",
    select: "Selecione abaixo",
    loading: "Carregando...",
    noQuestions: "Não há perguntas nesta categoria.",
    questionDate: "Última atualização:",
    backButton: "Voltar à pesquisa por categoria",
    categorynotfound: "Categoria não encontrada.",
    viewedHistory: "Ver histórico de visualização",
    noHistory: "Não há histórico de visualização.",
    viewDate: "Data de visualização:",
    clear: "Limpar histórico",
    questionhistory: "Histórico de perguntas",
    publicerror: "Falha ao alterar o status de publicação.",
    changecategory: "Alterar categoria",
    selectcategory: "Selecione a categoria",
    moveto: "Mover para a categoria:",
    cancel: "Cancelar",
    currentCategory: "Categoria atual",
    personal: "Pessoal",
    global: "Global",
    noNotifications: "Nenhuma notificação.",
    questionmanagement: "Gerenciamento de perguntas",
    newChat: "Novo chat",
    threads: "Tópicos",
    noThreads: "Ainda não há tópicos",
    renameThread: "Renomear tópico",
    confirmDeleteThread: "Deseja excluir este tópico?",
    threadDeletedSuccess: "Tópico excluído",
    threadDeletedDescription: "O tópico foi excluído com sucesso",
    threadDeletedError: "Falha ao excluir o tópico",
    threadDeletedErrorDescription: "Ocorreu um erro. Tente novamente.",
    similarityLabel: "Nível de filtragem",
    similarityDefaultLabel: "Padrão",
    similarityLow: "Fraco",
    similarityHigh: "Forte",
    screenSize: "Tamanho da tela",
    widthSmall: "Pequeno",
    widthMedium: "Médio",
    widthLarge: "Grande",
    register: "Q&A registrado",
    qtext: "Pergunta:",
    unpublic: "Não público",
    unofficial: "Não oficial",
    close: "Fechar",
    questionerror: "Por favor, insira uma pergunta.",
    answererror: "Por favor, insira uma resposta.",
    register_question: "Registrar Q&A",
    edit: "Editar",
    save: "Salvar",
    give_official: "Marcar como oficial",
    takeaway_official: "Remover marca oficial",
    delete: "Excluir",
    confirmDelete: "Tem certeza de que deseja excluir esta pergunta?",
    answerupdated: "Resposta atualizada!",
    unofficialize: "Remover a marca oficial?",
    officialize: "Marcar como oficial?",
    categorychanged: "Categoria alterada!",
    failtochangecategory: "Falha ao alterar a categoria.",
    nickname: "Nome",
    password: "Senha",
    login: "Entrar",
    registerPrompt: "↓↓↓↓ Clique aqui para se registrar ↓↓↓↓",
    successLogin: "Login realizado com sucesso!",
    signUp: "Registrar-se",
    age: "Idade",
    gender: "Gênero",
    spokenLanguage: "Idioma falado",
    male: "Masculino",
    female: "Feminino",
    other: "Outro",
    errorEmptyFields: "Digite o nome e a senha.",
    errorInvalidLogin: "Nome ou senha incorretos.",
    errorServer: "Falha no login. Digite o nome e a senha corretos.",
    errorAllFields: "Preencha todos os campos!",
    successRegistration: "Registro concluído!",
    errorRegistration: "Falha no registro",
    selectLanguage: "Selecione o idioma",
    editor: "Editor",
    openInAdmin: "Abrir no Gerenciamento de Perguntas",
    historyOpen: "Ver respostas anteriores",
    historyClose: "Fechar histórico",
    historyEmpty: "Não há histórico.",
    diffShow: "Mostrar diferenças",
    diffHide: "Ocultar diferenças",
    diffCaption: "Diferenças entre esta versão e a próxima",
    actionButton: "Ação",
    actionTranslate: "Traduzir",
    actionSummarize: "Resumir",
    actionSimplify: "Simplificar",
    actionApplied: "O resultado da ação foi aplicado ao campo de entrada",
    actionLabel: "Ação",
    noRecentAnswer: "Nenhuma resposta recente",
    actionApplyPrefix: "",
    actionApplySuffix: " aplicado",
    notSelected: "Nada selecionado",
    // Tooltips
    tooltipHome: "Tela inicial",
    tooltipKeywordSearch: "Pesquisar por palavra-chave",
    tooltipCategorySearch: "Pesquisar por categoria",
    tooltipQuestionManagement: "Gerenciar perguntas",
    tooltipNotifications: "Ver notificações",
    tooltipLanguageSelect: "Alterar idioma de exibição",
    tooltipSidebarToggle: "Mostrar/ocultar a barra lateral",
    tooltipUserMenu: "Abrir menu do usuário",
  },
  es: { // スペイン語
    home: "Inicio",
    keyword: "Búsqueda por palabra clave",
    logout: "Cerrar sesión",
    menu: "Menú",
    welcome: "¡Bienvenido!",
    guest: "Invitado",
    askQuestion: "Haz una pregunta",
    disclaimer: "La información de ShigaChat puede no ser precisa",
    questionLabel: "Escribe tu pregunta:",
    placeholder: "Escribe tu pregunta aquí...",
    askButton: "Preguntar",
    generatingAnswer: "Generando respuesta...",
    answer: "Respuesta:",
    similarQuestions: "Preguntas y respuestas consultadas:",
    noSimilarWarning: "No se encontraron preguntas similares. La respuesta puede no ser precisa.",
    sortByDate: "Por fecha",
    sortBySimilarity: "Por similitud",
    registerquestion: "🛠️ Registrar Q&A",
    error: "Ocurrió un error:",
    official: "Oficial",
    publicToggle: "Público",
    privateToggle: "Privado",
    makepublicToggle: "Hacer pública la pregunta",
    makeprivateToggle: "No hacer pública la pregunta",
    enterquestion: "Ingrese una pregunta",
    failedtopost: "Error al publicar la pregunta",
    failtogetanswer: "Error al obtener la respuesta",
    failtoupdate: "Error al actualizar.",
    timeUnknown: "Fecha/hora desconocida",
    keywordSearch: "Búsqueda por palabra clave",
    enterKeyword: "Ingrese una palabra clave...",
    search: "Buscar",
    noResults: "No se encontraron resultados.",
    errorLogin: "Es necesario iniciar sesión.",
    keyworderror: "Error de palabra clave",
    category: "Categoría",
    categorySearch: "Búsqueda por categoría",
    select: "Seleccione abajo",
    loading: "Cargando...",
    noQuestions: "No hay preguntas en esta categoría.",
    questionDate: "Última actualización:",
    backButton: "Volver a la búsqueda por categoría",
    categorynotfound: "Categoría no encontrada.",
    viewedHistory: "Ver historial de vistas",
    noHistory: "No hay historial de vistas.",
    viewDate: "Fecha de visualización:",
    clear: "Borrar historial",
    questionhistory: "Historial de preguntas",
    publicerror: "Error al cambiar el estado público.",
    changecategory: "Cambiar categoría",
    selectcategory: "Seleccione la categoría",
    moveto: "Mover a la categoría:",
    cancel: "Cancelar",
    currentCategory: "Categoría actual",
    personal: "Personal",
    global: "Global",
    noNotifications: "No hay notificaciones.",
    questionmanagement: "Gestión de preguntas",
    newChat: "Nuevo chat",
    threads: "Hilos",
    noThreads: "Aún no hay hilos",
    renameThread: "Renombrar hilo",
    confirmDeleteThread: "¿Desea eliminar este hilo?",
    threadDeletedSuccess: "Hilo eliminado",
    threadDeletedDescription: "El hilo se eliminó correctamente",
    threadDeletedError: "Error al eliminar el hilo",
    threadDeletedErrorDescription: "Ocurrió un error. Inténtalo de nuevo.",
    similarityLabel: "Nivel de filtrado",
    similarityDefaultLabel: "Predeterminado",
    similarityLow: "Débil",
    similarityHigh: "Fuerte",
    screenSize: "Tamaño de pantalla",
    widthSmall: "Pequeño",
    widthMedium: "Mediano",
    widthLarge: "Grande",
    register: "Q&A registrado",
    qtext: "Pregunta:",
    unpublic: "No público",
    unofficial: "No oficial",
    close: "Cerrar",
    questionerror: "Por favor, ingrese una pregunta.",
    answererror: "Por favor, ingrese una respuesta.",
    register_question: "Registrar Q&A",
    edit: "Editar",
    save: "Guardar",
    give_official: "Marcar como oficial",
    takeaway_official: "Quitar marca oficial",
    delete: "Eliminar",
    confirmDelete: "¿Seguro que desea eliminar esta pregunta?",
    answerupdated: "¡Respuesta actualizada!",
    unofficialize: "¿Quitar la marca oficial?",
    officialize: "¿Marcar como oficial?",
    categorychanged: "¡Categoría cambiada!",
    failtochangecategory: "Error al cambiar la categoría.",
    nickname: "Nombre",
    password: "Contraseña",
    login: "Iniciar sesión",
    registerPrompt: "↓↓↓↓ Haga clic aquí para registrarse ↓↓↓↓",
    successLogin: "¡Inicio de sesión exitoso!",
    signUp: "Registrarse",
    age: "Edad",
    gender: "Género",
    spokenLanguage: "Idioma",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    errorEmptyFields: "Ingrese el nombre y la contraseña.",
    errorInvalidLogin: "Nombre o contraseña incorrectos.",
    errorServer: "Error de inicio de sesión. Ingrese el nombre y la contraseña correctos.",
    errorAllFields: "¡Complete todos los campos!",
    successRegistration: "¡Registro completo!",
    errorRegistration: "Error en el registro",
    selectLanguage: "Seleccionar idioma",
    editor: "Editor",
    openInAdmin: "Abrir en Gestión de Preguntas",
    historyOpen: "Ver respuestas anteriores",
    historyClose: "Cerrar historial",
    historyEmpty: "No hay historial.",
    diffShow: "Mostrar diferencias",
    diffHide: "Ocultar diferencias",
    diffCaption: "Diferencias entre esta versión y la siguiente",
    actionButton: "Acción",
    actionTranslate: "Traducir",
    actionSummarize: "Resumir",
    actionSimplify: "Simplificar",
    actionApplied: "El resultado de la acción fue aplicado al campo de entrada",
    actionLabel: "Acción",
    noRecentAnswer: "No hay respuestas recientes",
    actionApplyPrefix: "",
    actionApplySuffix: " aplicado",
    notSelected: "Nada seleccionado",
    // Tooltips
    tooltipHome: "Pantalla principal",
    tooltipKeywordSearch: "Buscar por palabra clave",
    tooltipCategorySearch: "Buscar por categoría",
    tooltipQuestionManagement: "Gestionar preguntas",
    tooltipNotifications: "Ver notificaciones",
    tooltipLanguageSelect: "Cambiar idioma de visualización",
    tooltipSidebarToggle: "Mostrar/ocultar barra lateral",
    tooltipUserMenu: "Abrir menú de usuario",
  },

  tl: { // タガログ語
    home: "Home",
    keyword: "Maghanap gamit ang keyword",
    logout: "Mag-logout",
    menu: "Menu",
    welcome: "Maligayang pagdating!",
    guest: "Bisita",
    askQuestion: "Magtanong",
    disclaimer: "Ang impormasyon ng ShigaChat ay maaaring hindi tumpak",
    questionLabel: "Ilagay ang iyong tanong:",
    placeholder: "Ilagay ang tanong dito...",
    askButton: "Itanong",
    generatingAnswer: "Gumagawa ng sagot...",
    answer: "Sagot:",
    similarQuestions: "Mga tanong at sagot na ginamit bilang sanggunian:",
    noSimilarWarning: "Walang katulad na tanong. Maaaring hindi tama ang sagot.",
    sortByDate: "Ayon sa petsa",
    sortBySimilarity: "Ayon sa pagkakahawig",
    registerquestion: "🛠️ Magrehistro ng Q&A",
    error: "Nagkaroon ng error:",
    official: "Opisyal",
    publicToggle: "Pampubliko",
    privateToggle: "Pribado",
    makepublicToggle: "Gawing pampubliko ang tanong",
    makeprivateToggle: "Huwag gawing pampubliko ang tanong",
    enterquestion: "Ilagay ang tanong",
    failedtopost: "Nabigo ang pag-post ng tanong",
    failtogetanswer: "Nabigo ang pagkuha ng sagot",
    failtoupdate: "Nabigo ang pag-update.",
    timeUnknown: "Hindi alam ang petsa/oras",
    keywordSearch: "Paghahanap gamit ang keyword",
    enterKeyword: "Ilagay ang keyword...",
    search: "Maghanap",
    noResults: "Walang resulta.",
    errorLogin: "Kailangan mag-login.",
    keyworderror: "Error sa keyword",
    category: "Kategorya",
    categorySearch: "Paghahanap ayon sa kategorya",
    select: "Pumili sa ibaba",
    loading: "Naglo-load...",
    noQuestions: "Walang tanong sa kategoryang ito.",
    questionDate: "Huling na-update:",
    backButton: "Bumalik sa paghahanap ng kategorya",
    categorynotfound: "Hindi natagpuan ang kategorya.",
    viewedHistory: "Tingnan ang kasaysayan ng mga tanong",
    noHistory: "Walang kasaysayan.",
    viewDate: "Petsa ng pagtingin:",
    clear: "I-clear ang kasaysayan",
    questionhistory: "Kasaysayan ng tanong",
    publicerror: "Nabigo sa pagbabago ng estado ng publikasyon.",
    changecategory: "Baguhin ang kategorya",
    selectcategory: "Pumili ng kategorya",
    moveto: "Ilipat sa kategorya:",
    cancel: "Kanselahin",
    currentCategory: "Kasalukuyang kategorya",
    personal: "Personal",
    global: "Global",
    noNotifications: "Walang notipikasyon.",
    questionmanagement: "Pamamahala ng tanong",
    newChat: "Bagong chat",
    threads: "Mga thread",
    noThreads: "Wala pang mga thread",
    renameThread: "Palitan ang pangalan ng thread",
    confirmDeleteThread: "Burahin ang thread na ito?",
    threadDeletedSuccess: "Nabura ang thread",
    threadDeletedDescription: "Matagumpay na nabura ang thread",
    threadDeletedError: "Nabigo ang pagbura ng thread",
    threadDeletedErrorDescription: "Nagkaroon ng error. Subukan muli.",
    similarityLabel: "Antas ng filter",
    similarityDefaultLabel: "Default",
    similarityLow: "Mahina",
    similarityHigh: "Malakas",
    screenSize: "Laki ng screen",
    widthSmall: "Maliit",
    widthMedium: "Katamtaman",
    widthLarge: "Malaki",
    register: "Na-rehistro ang Q&A",
    qtext: "Tanong:",
    unpublic: "Hindi publiko",
    unofficial: "Hindi opisyal",
    close: "Isara",
    questionerror: "Pakilagay ang tanong.",
    answererror: "Pakilagay ang sagot.",
    register_question: "Magrehistro ng Q&A",
    edit: "I-edit",
    save: "I-save",
    give_official: "Gawing opisyal",
    takeaway_official: "Tanggalin ang marka ng opisyal",
    delete: "Burahin",
    confirmDelete: "Sigurado ka bang buburahin ang tanong na ito?",
    answerupdated: "Na-update ang sagot!",
    unofficialize: "Tanggalin ang opisyal na marka?",
    officialize: "Gawing opisyal?",
    categorychanged: "Nabago ang kategorya!",
    failtochangecategory: "Nabigo ang pagbabago ng kategorya.",
    nickname: "Pangalan",
    password: "Password",
    login: "Mag-login",
    registerPrompt: "↓↓↓↓ Magrehistro dito ↓↓↓↓",
    successLogin: "Matagumpay ang login!",
    signUp: "Mag-sign up",
    age: "Edad",
    gender: "Kasarian",
    spokenLanguage: "Wikang ginagamit",
    male: "Lalaki",
    female: "Babae",
    other: "Iba pa",
    errorEmptyFields: "Ilagay ang pangalan at password.",
    errorInvalidLogin: "Mali ang pangalan o password.",
    errorServer: "Nabigo ang login. Ilagay ang tamang pangalan at password.",
    errorAllFields: "Punan lahat ng mga field!",
    successRegistration: "Matagumpay ang pagrerehistro!",
    errorRegistration: "Nabigo ang pagrerehistro",
    selectLanguage: "Pumili ng wika",
    editor: "Editor",
    openInAdmin: "Buksan sa Pamamahala ng Tanong",
    historyOpen: "Tingnan ang mga nakaraang sagot",
    historyClose: "Isara ang kasaysayan",
    historyEmpty: "Walang kasaysayan.",
    diffShow: "Ipakita ang pagkakaiba",
    diffHide: "Itago ang pagkakaiba",
    diffCaption: "Pagkakaiba mula sa bersyong ito hanggang sa susunod",
    actionButton: "Aksyon",
    actionTranslate: "Isalin",
    actionSummarize: "Ibuod",
    actionSimplify: "Pasimplehin",
    actionApplied: "Naidagdag ang resulta sa field ng input",
    actionLabel: "Aksyon",
    noRecentAnswer: "Walang kamakailang sagot",
    actionApplyPrefix: "",
    actionApplySuffix: " inilapat",
    notSelected: "Walang napili",
    // Tooltips
    tooltipHome: "Home screen",
    tooltipKeywordSearch: "Maghanap gamit ang keyword",
    tooltipCategorySearch: "Maghanap ayon sa kategorya",
    tooltipQuestionManagement: "Pamahalaan ang mga tanong",
    tooltipNotifications: "Tingnan ang mga notipikasyon",
    tooltipLanguageSelect: "Palitan ang wika ng display",
    tooltipSidebarToggle: "Ipakita/itago ang sidebar",
    tooltipUserMenu: "Buksan ang menu ng user",
  },

  id: { // インドネシア語
    home: "Beranda",
    keyword: "Pencarian kata kunci",
    logout: "Keluar",
    menu: "Menu",
    welcome: "Selamat datang!",
    guest: "Tamu",
    askQuestion: "Ajukan pertanyaan",
    disclaimer: "Informasi di ShigaChat mungkin tidak akurat",
    questionLabel: "Masukkan pertanyaan:",
    placeholder: "Tulis pertanyaan di sini...",
    askButton: "Tanya",
    generatingAnswer: "Sedang membuat jawaban...",
    answer: "Jawaban:",
    similarQuestions: "Pertanyaan dan jawaban terkait:",
    noSimilarWarning: "Tidak ada pertanyaan serupa. Jawaban mungkin tidak akurat.",
    sortByDate: "Urutkan berdasarkan tanggal",
    sortBySimilarity: "Urutkan berdasarkan kemiripan",
    registerquestion: "🛠️ Daftarkan Q&A",
    error: "Terjadi kesalahan:",
    official: "Resmi",
    publicToggle: "Publik",
    privateToggle: "Pribadi",
    makepublicToggle: "Buat pertanyaan publik",
    makeprivateToggle: "Jangan buat pertanyaan publik",
    enterquestion: "Masukkan pertanyaan",
    failedtopost: "Gagal mengirim pertanyaan",
    failtogetanswer: "Gagal mendapatkan jawaban",
    failtoupdate: "Gagal memperbarui.",
    timeUnknown: "Tanggal/waktu tidak diketahui",
    keywordSearch: "Pencarian kata kunci",
    enterKeyword: "Masukkan kata kunci...",
    search: "Cari",
    noResults: "Tidak ada hasil.",
    errorLogin: "Login diperlukan.",
    keyworderror: "Kesalahan kata kunci",
    category: "Kategori",
    categorySearch: "Pencarian berdasarkan kategori",
    select: "Pilih dari bawah",
    loading: "Memuat...",
    noQuestions: "Tidak ada pertanyaan dalam kategori ini.",
    questionDate: "Terakhir diperbarui:",
    backButton: "Kembali ke pencarian kategori",
    categorynotfound: "Kategori tidak ditemukan.",
    viewedHistory: "Lihat riwayat",
    noHistory: "Tidak ada riwayat.",
    viewDate: "Tanggal dilihat:",
    clear: "Hapus riwayat",
    questionhistory: "Riwayat pertanyaan",
    publicerror: "Gagal mengubah status publik.",
    changecategory: "Ubah kategori",
    selectcategory: "Pilih kategori",
    moveto: "Pindahkan ke kategori:",
    cancel: "Batal",
    currentCategory: "Kategori saat ini",
    personal: "Pribadi",
    global: "Global",
    noNotifications: "Tidak ada notifikasi.",
    questionmanagement: "Manajemen pertanyaan",
    newChat: "Chat baru",
    threads: "Thread",
    noThreads: "Belum ada thread",
    renameThread: "Ganti nama thread",
    confirmDeleteThread: "Hapus thread ini?",
    threadDeletedSuccess: "Thread berhasil dihapus",
    threadDeletedDescription: "Thread berhasil dihapus",
    threadDeletedError: "Gagal menghapus thread",
    threadDeletedErrorDescription: "Terjadi kesalahan. Coba lagi.",
    similarityLabel: "Tingkat filter",
    similarityDefaultLabel: "Default",
    similarityLow: "Rendah",
    similarityHigh: "Tinggi",
    screenSize: "Ukuran layar",
    widthSmall: "Kecil",
    widthMedium: "Sedang",
    widthLarge: "Besar",
    register: "Q&A terdaftar",
    qtext: "Pertanyaan:",
    unpublic: "Tidak publik",
    unofficial: "Tidak resmi",
    close: "Tutup",
    questionerror: "Silakan masukkan pertanyaan.",
    answererror: "Silakan masukkan jawaban.",
    register_question: "Daftarkan Q&A",
    edit: "Edit",
    save: "Simpan",
    give_official: "Tandai sebagai resmi",
    takeaway_official: "Hapus tanda resmi",
    delete: "Hapus",
    confirmDelete: "Yakin ingin menghapus pertanyaan ini?",
    answerupdated: "Jawaban diperbarui!",
    unofficialize: "Hapus tanda resmi?",
    officialize: "Tandai sebagai resmi?",
    categorychanged: "Kategori diubah!",
    failtochangecategory: "Gagal mengubah kategori.",
    nickname: "Nama",
    password: "Kata sandi",
    login: "Masuk",
    registerPrompt: "↓↓↓↓ Klik di sini untuk mendaftar ↓↓↓↓",
    successLogin: "Login berhasil!",
    signUp: "Daftar",
    age: "Usia",
    gender: "Jenis kelamin",
    spokenLanguage: "Bahasa",
  }


};


export const categoryList = [
  { 
    id: 1, 
    name: { 
      ja: "在留・住民手続", 
      en: "Immigration & Residency Procedures", 
      vi: "Thủ tục cư trú & dân cư", 
      zh: "居留及居民手续", 
      ko: "体류 및 주민 절차", 
      pt: "Procedimento de imigração e de residência", 
      es: "Procedimientos de inmigración y de residentes", 
      tl: "Mga Pamamaraan sa Imigrasyon at Paninirahan", 
      id: "Izin Tinggal & Prosedur Tinggal" 
    }, 
    className: "category-zairyu" 
  },
  { 
    id: 2, 
    name: { 
      ja: "生活", 
      en: "Daily Life", 
      vi: "Đời sống hằng ngày", 
      zh: "生活", 
      ko: "생활", 
      pt: "Vida", 
      es: "Vida", 
      tl: "Pamumuhay", 
      id: "Kehidupan sehari-hari" 
    }, 
    className: "category-seikatsu" 
  },
  { 
    id: 3, 
    name: { 
      ja: "医療", 
      en: "Healthcare", 
      vi: "Y tế", 
      zh: "医疗", 
      ko: "의료", 
      pt: "Médico", 
      es: "Médica", 
      tl: "Pangangalagang Medikal", 
      id: "Medis" 
    }, 
    className: "category-iryo" 
  },
  { 
    id: 4, 
    name: { 
      ja: "年金・保険", 
      en: "Pension & Insurance", 
      vi: "Lương hưu & bảo hiểm", 
      zh: "养老金与保险", 
      ko: "연금 및 보험", 
      pt: "Pensões e seguros", 
      es: "Pensiones y seguros", 
      tl: "Pensiyon at Seguro", 
      id: "Pensiun" 
    }, 
    className: "category-nenkin" 
  },
  { 
    id: 5, 
    name: { 
      ja: "労働", 
      en: "Labor", 
      vi: "Lao động", 
      zh: "劳动", 
      ko: "노동", 
      pt: "Trabalho", 
      es: "Trabajo", 
      tl: "Trabaho", 
      id: "Ketenagakerjaan" 
    }, 
    className: "category-roudou" 
  },
  { 
    id: 6, 
    name: { 
      ja: "教育", 
      en: "Education", 
      vi: "Giáo dục", 
      zh: "教育", 
      ko: "교육", 
      pt: "Educação", 
      es: "Educación", 
      tl: "Edukasyon", 
      id: "Pendidikan" 
    }, 
    className: "category-kyouiku" 
  },
  { 
    id: 7, 
    name: { 
      ja: "結婚・離婚", 
      en: "Marriage & Divorce", 
      vi: "Kết hôn & ly hôn", 
      zh: "婚姻与离婚", 
      ko: "결婚 및 이혼", 
      pt: "Casamento e divórcio", 
      es: "Matrimonio y divorcio", 
      tl: "Kasal at Diborsiyo", 
      id: "Pernikahan dan Perceraian" 
    }, 
    className: "category-kekkon" 
  },
  { 
    id: 8, 
    name: { 
      ja: "出産・育児", 
      en: "Childbirth & Childcare", 
      vi: "Sinh con & nuôi dạy con", 
      zh: "生育与育儿", 
      ko: "출산 및 육아", 
      pt: "Parto e puericultura", 
      es: "El parto y el cuidado infantil", 
      tl: "Panganganak at Pag-aalaga ng Bata", 
      id: "Melahirkan dan Mengasuh Anak" 
    }, 
    className: "category-shussan" 
  },
  { 
    id: 9, 
    name: { 
      ja: "住宅", 
      en: "Housing", 
      vi: "Nhà ở", 
      zh: "住宅", 
      ko: "주거", 
      pt: "Habitação", 
      es: "Vivienda", 
      tl: "Pabahay", 
      id: "Hunian" 
    }, 
    className: "category-jutaku" 
  },
  { 
    id: 10, 
    name: { 
      ja: "税金", 
      en: "Taxes", 
      vi: "Thuế", 
      zh: "税务", 
      ko: "세금", 
      pt: "Impostos", 
      es: "Impuestos", 
      tl: "Buwis", 
      id: "Pajak" 
    }, 
    className: "category-zeikin" 
  },
  { 
    id: 11, 
    name: { 
      ja: "福祉", 
      en: "Welfare", 
      vi: "Phúc lợi", 
      zh: "福利", 
      ko: "복지", 
      pt: "Bem-estar", 
      es: "Bienstar", 
      tl: "Kapakanan", 
      id: "Welfare" 
    }, 
    className: "category-fukushi" 
  },
  { 
    id: 12, 
    name: { 
      ja: "事件・事故", 
      en: "Incidents & Accidents", 
      vi: "Sự cố & tai nạn", 
      zh: "事件及事故", 
      ko: "사건 및 사고", 
      pt: "Incidentes e acidentes", 
      es: "Incidentes y accidentes", 
      tl: "Mga Insidente at Aksidente", 
      id: "Kasus Kriminal dan Kecelakaan" 
    }, 
    className: "category-jiken" 
  },
  { 
    id: 13, 
    name: { 
      ja: "災害", 
      en: "Disasters", 
      vi: "Thiên tai", 
      zh: "灾害", 
      ko: "재난", 
      pt: "Desastre", 
      es: "Desastre", 
      tl: "Kalamidad", 
      id: "Bencana" 
    }, 
    className: "category-saigai" 
  },
];


export const languageCodeToId = { 
  ja: 1, 
  en: 2, 
  vi: 3, 
  zh: 4, 
  ko: 5, 
  pt: 6, 
  es: 7, 
  tl: 8, 
  id: 9 
};

export const languageLabelToCode = {
  日本語: "ja",
  English: "en",
  "Tiếng Việt": "vi",
  中文: "zh",
  한국어: "ko",
  Português: "pt",
  Español: "es",
  "Tagalog": "tl",
  Bahasa: "id"
};

export const languageCodeToLabel = Object.fromEntries(
  Object.entries(languageLabelToCode).map(([label, code]) => [code, label])
);
