from __future__ import annotations

from typing import Protocol

from domain.conversation.models import ChatTurn, Thread


class ThreadRepository(Protocol):
    def create(self, user_id: int) -> Thread: ...

    def find_by_id(self, thread_id: int) -> Thread | None: ...

    def list_by_user(self, user_id: int) -> list[Thread]: ...

    def touch(self, thread_id: int, title: str | None = None) -> None: ...

    def delete(self, thread_id: int) -> None: ...


class ChatTurnRepository(Protocol):
    def append(self, turn: ChatTurn) -> ChatTurn: ...

    def list_by_thread(self, thread_id: int) -> list[ChatTurn]: ...

    def list_recent_by_thread(self, thread_id: int, limit: int) -> list[ChatTurn]: ...

    def delete_by_thread(self, thread_id: int) -> None: ...
